In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder, OneHotEncoder
import pickle

In [2]:

## Load the dataset
data=pd.read_csv("Car_sell_Dataset.csv")
data.head()

,Brand,Model_Name,Model_Variant,Car_Type,Transmission,Fuel_Type,Year,Kilometers,Owner,State,Accidental,Price
0,Mahindra,TUV300,AX5,SUV,Manual,CNG,2017,164654,1st,Rajasthan,No,547253
1,Skoda,Rapid,Style,Sedan,Manual,Petrol,2018,41351,1st,Maharashtra,No,512050
2,Maruti Suzuki,Alto,Z,Hatchback,Manual,Diesel,2002,119090,3rd+,Tamil Nadu,No,678923
3,Hyundai,Grand i10,Magna,Hatchback,Manual,Diesel,2013,19979,1st,Andhra Pradesh,No,522500
4,Mahindra,XUV500,W8,SUV,Manual,Petrol,2011,130591,3rd+,Bihar,No,401182

In [3]:

## Encode categorical variables
label_encoder_transmission=LabelEncoder()
data['Transmission']=label_encoder_transmission.fit_transform(data['Transmission'])
data

,Brand,Model_Name,Model_Variant,Car_Type,Transmission,Fuel_Type,Year,Kilometers,Owner,State,Accidental,Price
0,Mahindra,TUV300,AX5,SUV,1,CNG,2017,164654,1st,Rajasthan,No,547253
1,Skoda,Rapid,Style,Sedan,1,Petrol,2018,41351,1st,Maharashtra,No,512050
2,Maruti Suzuki,Alto,Z,Hatchback,1,Diesel,2002,119090,3rd+,Tamil Nadu,No,678923
3,Hyundai,Grand i10,Magna,Hatchback,1,Diesel,2013,19979,1st,Andhra Pradesh,No,522500
4,Mahindra,XUV500,W8,SUV,1,Petrol,2011,130591,3rd+,Bihar,No,401182
...,...,...,...,...,...,...,...,...,...,...,...,...
140899,Mahindra,Scorpio,W11,SUV,1,Petrol,2002,62699,1st,Telangana,No,221067
140900,Hyundai,i10,Era,Hatchback,1,Petrol,2013,47953,2nd,Maharashtra,No,745360
140901,Honda,Jazz,V,Sedan,0,Diesel,2009,134566,3rd+,Odisha,No,122852
140902,Honda,WR-V,E,SUV,1,Diesel,2022,88697,1st,Gujarat,No,502425
140903,Chevrolet,Tavera,Base,MPV,1,Diesel,2009,48117,2nd,Gujarat,No,905080

In [4]:

## Encode categorical variables
label_encoder_accidental=LabelEncoder()
data['Accidental']=label_encoder_accidental.fit_transform(data['Accidental'])
data

,Brand,Model_Name,Model_Variant,Car_Type,Transmission,Fuel_Type,Year,Kilometers,Owner,State,Accidental,Price
0,Mahindra,TUV300,AX5,SUV,1,CNG,2017,164654,1st,Rajasthan,0,547253
1,Skoda,Rapid,Style,Sedan,1,Petrol,2018,41351,1st,Maharashtra,0,512050
2,Maruti Suzuki,Alto,Z,Hatchback,1,Diesel,2002,119090,3rd+,Tamil Nadu,0,678923
3,Hyundai,Grand i10,Magna,Hatchback,1,Diesel,2013,19979,1st,Andhra Pradesh,0,522500
4,Mahindra,XUV500,W8,SUV,1,Petrol,2011,130591,3rd+,Bihar,0,401182
...,...,...,...,...,...,...,...,...,...,...,...,...
140899,Mahindra,Scorpio,W11,SUV,1,Petrol,2002,62699,1st,Telangana,0,221067
140900,Hyundai,i10,Era,Hatchback,1,Petrol,2013,47953,2nd,Maharashtra,0,745360
140901,Honda,Jazz,V,Sedan,0,Diesel,2009,134566,3rd+,Odisha,0,122852
140902,Honda,WR-V,E,SUV,1,Diesel,2022,88697,1st,Gujarat,0,502425
140903,Chevrolet,Tavera,Base,MPV,1,Diesel,2009,48117,2nd,Gujarat,0,905080

In [5]:
## Onehot encode Brand
onehot_encoder_brand=OneHotEncoder()
brand_encoder=onehot_encoder_brand.fit_transform(data[['Brand']]).toarray()
onehot_encoder_brand.get_feature_names_out(['Brand'])
brand_encoded_df=pd.DataFrame(brand_encoder,columns=onehot_encoder_brand.get_feature_names_out(['Brand']))
brand_encoded_df

,Brand_Audi,Brand_BMW,Brand_Chevrolet,Brand_Ford,Brand_Honda,Brand_Hyundai,Brand_Jaguar,Brand_Kia,Brand_MG,Brand_Mahindra,Brand_Maruti Suzuki,Brand_Nissan,Brand_Range Rover,Brand_Renault,Brand_Skoda,Brand_Tata,Brand_Toyota,Brand_Volkswagen
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140899,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140900,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140901,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140902,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140903,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Brand',axis=1),brand_encoded_df],axis=1)
data.head()

,Model_Name,Model_Variant,Car_Type,Transmission,Fuel_Type,Year,Kilometers,Owner,State,Accidental,...,Brand_MG,Brand_Mahindra,Brand_Maruti Suzuki,Brand_Nissan,Brand_Range Rover,Brand_Renault,Brand_Skoda,Brand_Tata,Brand_Toyota,Brand_Volkswagen
0,TUV300,AX5,SUV,1,CNG,2017,164654,1st,Rajasthan,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Rapid,Style,Sedan,1,Petrol,2018,41351,1st,Maharashtra,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,Alto,Z,Hatchback,1,Diesel,2002,119090,3rd+,Tamil Nadu,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Grand i10,Magna,Hatchback,1,Diesel,2013,19979,1st,Andhra Pradesh,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,XUV500,W8,SUV,1,Petrol,2011,130591,3rd+,Bihar,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
## Onehot encode 'Fuel_Type
onehot_encoder_fuel_type=OneHotEncoder()
fuel_type_encoder=onehot_encoder_fuel_type.fit_transform(data[['Fuel_Type']]).toarray()
onehot_encoder_fuel_type.get_feature_names_out(['Fuel_Type'])
fuel_type_encoded_df=pd.DataFrame(fuel_type_encoder,columns=onehot_encoder_fuel_type.get_feature_names_out(['Fuel_Type']))
fuel_type_encoded_df

,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol
0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...
140899,0.0,0.0,0.0,0.0,1.0
140900,0.0,0.0,0.0,0.0,1.0
140901,0.0,1.0,0.0,0.0,0.0
140902,0.0,1.0,0.0,0.0,0.0
140903,0.0,1.0,0.0,0.0,0.0

In [8]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Fuel_Type',axis=1),fuel_type_encoded_df],axis=1)
data

,Model_Name,Model_Variant,Car_Type,Transmission,Year,Kilometers,Owner,State,Accidental,Price,...,Brand_Renault,Brand_Skoda,Brand_Tata,Brand_Toyota,Brand_Volkswagen,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol
0,TUV300,AX5,SUV,1,2017,164654,1st,Rajasthan,0,547253,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,Rapid,Style,Sedan,1,2018,41351,1st,Maharashtra,0,512050,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,Alto,Z,Hatchback,1,2002,119090,3rd+,Tamil Nadu,0,678923,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,Grand i10,Magna,Hatchback,1,2013,19979,1st,Andhra Pradesh,0,522500,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,XUV500,W8,SUV,1,2011,130591,3rd+,Bihar,0,401182,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140899,Scorpio,W11,SUV,1,2002,62699,1st,Telangana,0,221067,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
140900,i10,Era,Hatchback,1,2013,47953,2nd,Maharashtra,0,745360,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
140901,Jazz,V,Sedan,0,2009,134566,3rd+,Odisha,0,122852,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
140902,WR-V,E,SUV,1,2022,88697,1st,Gujarat,0,502425,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
140903,Tavera,Base,MPV,1,2009,48117,2nd,Gujarat,0,905080,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [9]:
## Onehot encode Model_Name
onehot_encoder_model_name=OneHotEncoder()
model_name_encoder=onehot_encoder_model_name.fit_transform(data[['Model_Name']]).toarray()
onehot_encoder_model_name.get_feature_names_out(['Model_Name'])
model_name_encoded_df=pd.DataFrame(model_name_encoder,columns=onehot_encoder_model_name.get_feature_names_out(['Model_Name']))
model_name_encoded_df

,Model_Name_3 Series,Model_Name_5 Series,Model_Name_A4,Model_Name_A6,Model_Name_Alto,Model_Name_Altroz,Model_Name_Amaze,Model_Name_Ameo,Model_Name_Aspire,Model_Name_Astor,...,Model_Name_WR-V,Model_Name_WagonR,Model_Name_X1,Model_Name_X3,Model_Name_XE,Model_Name_XF,Model_Name_XUV500,Model_Name_ZS EV,Model_Name_i10,Model_Name_i20
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140899,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140900,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
140901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Model_Name',axis=1),model_name_encoded_df],axis=1)
data

,Model_Variant,Car_Type,Transmission,Year,Kilometers,Owner,State,Accidental,Price,Brand_Audi,...,Model_Name_WR-V,Model_Name_WagonR,Model_Name_X1,Model_Name_X3,Model_Name_XE,Model_Name_XF,Model_Name_XUV500,Model_Name_ZS EV,Model_Name_i10,Model_Name_i20
0,AX5,SUV,1,2017,164654,1st,Rajasthan,0,547253,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Style,Sedan,1,2018,41351,1st,Maharashtra,0,512050,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Z,Hatchback,1,2002,119090,3rd+,Tamil Nadu,0,678923,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Magna,Hatchback,1,2013,19979,1st,Andhra Pradesh,0,522500,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,W8,SUV,1,2011,130591,3rd+,Bihar,0,401182,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140899,W11,SUV,1,2002,62699,1st,Telangana,0,221067,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140900,Era,Hatchback,1,2013,47953,2nd,Maharashtra,0,745360,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
140901,V,Sedan,0,2009,134566,3rd+,Odisha,0,122852,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140902,E,SUV,1,2022,88697,1st,Gujarat,0,502425,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140903,Base,MPV,1,2009,48117,2nd,Gujarat,0,905080,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
## Onehot encode Model_Variant
onehot_encoder_model_variant=OneHotEncoder()
model_variant_encoder=onehot_encoder_model_variant.fit_transform(data[['Model_Variant']]).toarray()
onehot_encoder_model_variant.get_feature_names_out(['Model_Variant'])
model_variant_encoded_df=pd.DataFrame(model_variant_encoder,columns=onehot_encoder_model_variant.get_feature_names_out(['Model_Variant']))
model_variant_encoded_df

,Model_Variant_AX3,Model_Variant_AX5,Model_Variant_AX7,Model_Variant_Active,Model_Variant_Ambiente,Model_Variant_Ambition,Model_Variant_Asta,Model_Variant_Autobiography,Model_Variant_Base,Model_Variant_Comfortline,...,Model_Variant_XM,Model_Variant_XT,Model_Variant_XV,Model_Variant_XV Premium,Model_Variant_XV Premium (O),Model_Variant_XZ,Model_Variant_XZA,Model_Variant_XZA+,Model_Variant_Z,Model_Variant_ZX
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140899,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140900,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Model_Variant',axis=1),model_variant_encoded_df],axis=1)
data

,Car_Type,Transmission,Year,Kilometers,Owner,State,Accidental,Price,Brand_Audi,Brand_BMW,...,Model_Variant_XM,Model_Variant_XT,Model_Variant_XV,Model_Variant_XV Premium,Model_Variant_XV Premium (O),Model_Variant_XZ,Model_Variant_XZA,Model_Variant_XZA+,Model_Variant_Z,Model_Variant_ZX
0,SUV,1,2017,164654,1st,Rajasthan,0,547253,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Sedan,1,2018,41351,1st,Maharashtra,0,512050,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Hatchback,1,2002,119090,3rd+,Tamil Nadu,0,678923,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,Hatchback,1,2013,19979,1st,Andhra Pradesh,0,522500,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,SUV,1,2011,130591,3rd+,Bihar,0,401182,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140899,SUV,1,2002,62699,1st,Telangana,0,221067,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140900,Hatchback,1,2013,47953,2nd,Maharashtra,0,745360,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140901,Sedan,0,2009,134566,3rd+,Odisha,0,122852,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140902,SUV,1,2022,88697,1st,Gujarat,0,502425,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140903,MPV,1,2009,48117,2nd,Gujarat,0,905080,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
## Onehot encode Car_Type
onehot_encoder_car_type=OneHotEncoder()
car_type_encoder=onehot_encoder_car_type.fit_transform(data[['Car_Type']]).toarray()
onehot_encoder_car_type.get_feature_names_out(['Car_Type'])
car_type_encoded_df=pd.DataFrame(car_type_encoder,columns=onehot_encoder_car_type.get_feature_names_out(['Car_Type']))
car_type_encoded_df

,Car_Type_Hatchback,Car_Type_Luxury,Car_Type_MPV,Car_Type_SUV,Car_Type_Sedan
0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...
140899,0.0,0.0,0.0,1.0,0.0
140900,1.0,0.0,0.0,0.0,0.0
140901,0.0,0.0,0.0,0.0,1.0
140902,0.0,0.0,0.0,1.0,0.0
140903,0.0,0.0,1.0,0.0,0.0

In [14]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Car_Type',axis=1),car_type_encoded_df],axis=1)
data

,Transmission,Year,Kilometers,Owner,State,Accidental,Price,Brand_Audi,Brand_BMW,Brand_Chevrolet,...,Model_Variant_XZ,Model_Variant_XZA,Model_Variant_XZA+,Model_Variant_Z,Model_Variant_ZX,Car_Type_Hatchback,Car_Type_Luxury,Car_Type_MPV,Car_Type_SUV,Car_Type_Sedan
0,1,2017,164654,1st,Rajasthan,0,547253,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,2018,41351,1st,Maharashtra,0,512050,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1,2002,119090,3rd+,Tamil Nadu,0,678923,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1,2013,19979,1st,Andhra Pradesh,0,522500,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,1,2011,130591,3rd+,Bihar,0,401182,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140899,1,2002,62699,1st,Telangana,0,221067,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
140900,1,2013,47953,2nd,Maharashtra,0,745360,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
140901,0,2009,134566,3rd+,Odisha,0,122852,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
140902,1,2022,88697,1st,Gujarat,0,502425,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
140903,1,2009,48117,2nd,Gujarat,0,905080,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [15]:
## Onehot encode State
onehot_encoder_state=OneHotEncoder()
state_encoder=onehot_encoder_state.fit_transform(data[['State']]).toarray()
onehot_encoder_state.get_feature_names_out(['State'])
state_encoded_df=pd.DataFrame(state_encoder,columns=onehot_encoder_state.get_feature_names_out(['State']))
state_encoded_df

,State_Andhra Pradesh,State_Assam,State_Bihar,State_Chandigarh,State_Chhattisgarh,State_Delhi,State_Goa,State_Gujarat,State_Haryana,State_Himachal Pradesh,...,State_Odisha,State_Other UTs,State_Puducherry,State_Punjab,State_Rajasthan,State_Tamil Nadu,State_Telangana,State_Uttar Pradesh,State_Uttarakhand,State_West Bengal
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140899,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
140900,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('State',axis=1),state_encoded_df],axis=1)
data

,Transmission,Year,Kilometers,Owner,Accidental,Price,Brand_Audi,Brand_BMW,Brand_Chevrolet,Brand_Ford,...,State_Odisha,State_Other UTs,State_Puducherry,State_Punjab,State_Rajasthan,State_Tamil Nadu,State_Telangana,State_Uttar Pradesh,State_Uttarakhand,State_West Bengal
0,1,2017,164654,1st,0,547253,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1,2018,41351,1st,0,512050,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,2002,119090,3rd+,0,678923,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1,2013,19979,1st,0,522500,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,2011,130591,3rd+,0,401182,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140899,1,2002,62699,1st,0,221067,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
140900,1,2013,47953,2nd,0,745360,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140901,0,2009,134566,3rd+,0,122852,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140902,1,2022,88697,1st,0,502425,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140903,1,2009,48117,2nd,0,905080,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
## Onehot encode Owner
onehot_encoder_owner=OneHotEncoder()
owner_encoder=onehot_encoder_owner.fit_transform(data[['Owner']]).toarray()
onehot_encoder_owner.get_feature_names_out(['Owner'])
owner_encoded_df=pd.DataFrame(owner_encoder,columns=onehot_encoder_owner.get_feature_names_out(['Owner']))
owner_encoded_df

        Owner_1st  Owner_2nd  Owner_3rd+
0             1.0        0.0         0.0
1             1.0        0.0         0.0
2             0.0        0.0         1.0
3             1.0        0.0         0.0
4             0.0        0.0         1.0
...           ...        ...         ...
140899        1.0        0.0         0.0
140900        0.0        1.0         0.0
140901        0.0        0.0         1.0
140902        1.0        0.0         0.0
140903        0.0        1.0         0.0

[140904 rows x 3 columns]

In [18]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Owner',axis=1),owner_encoded_df],axis=1)
data

,Transmission,Year,Kilometers,Accidental,Price,Brand_Audi,Brand_BMW,Brand_Chevrolet,Brand_Ford,Brand_Honda,...,State_Punjab,State_Rajasthan,State_Tamil Nadu,State_Telangana,State_Uttar Pradesh,State_Uttarakhand,State_West Bengal,Owner_1st,Owner_2nd,Owner_3rd+
0,1,2017,164654,0,547253,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1,2018,41351,0,512050,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1,2002,119090,0,678923,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1,2013,19979,0,522500,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1,2011,130591,0,401182,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140899,1,2002,62699,0,221067,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
140900,1,2013,47953,0,745360,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
140901,0,2009,134566,0,122852,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
140902,1,2022,88697,0,502425,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
140903,1,2009,48117,0,905080,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [19]:
## Save the encoders and scaler
with open('label_encoder_accidental.pkl','wb') as file:
    pickle.dump(label_encoder_accidental,file)

with open('label_encoder_transmission.pkl','wb') as file:
    pickle.dump(label_encoder_transmission,file)

with open('onehot_encoder_brand.pkl','wb') as file:
    pickle.dump(onehot_encoder_brand,file)
    
with open('onehot_encoder_fuel_type.pkl','wb') as file:
    pickle.dump(onehot_encoder_fuel_type,file)

with open('onehot_encoder_model_name.pkl','wb') as file:
    pickle.dump(onehot_encoder_model_name,file)

with open('onehot_encoder_model_variant.pkl','wb') as file:
    pickle.dump(onehot_encoder_model_variant,file)

with open('onehot_encoder_car_type.pkl','wb') as file:
    pickle.dump(onehot_encoder_car_type,file)

with open('onehot_encoder_state.pkl','wb') as file:
    pickle.dump(onehot_encoder_state,file)

with open('onehot_encoder_owner.pkl','wb') as file:
    pickle.dump(onehot_encoder_owner,file)

In [20]:
data.head()

,Transmission,Year,Kilometers,Accidental,Price,Brand_Audi,Brand_BMW,Brand_Chevrolet,Brand_Ford,Brand_Honda,...,State_Punjab,State_Rajasthan,State_Tamil Nadu,State_Telangana,State_Uttar Pradesh,State_Uttarakhand,State_West Bengal,Owner_1st,Owner_2nd,Owner_3rd+
0,1,2017,164654,0,547253,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1,2018,41351,0,512050,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1,2002,119090,0,678923,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1,2013,19979,0,522500,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1,2011,130591,0,401182,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [21]:
## DiVide the dataset into indepent and dependent features
X=data.drop('Price',axis=1)
y=data['Price']

## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [22]:
X_train

array([[ 0.41870278,  0.59411333,  0.48592817, ...,  0.9315193 ,
        -0.81816963, -0.26062993],
       [ 0.41870278,  0.98581513, -1.48411528, ...,  0.9315193 ,
        -0.81816963, -0.26062993],
       [ 0.41870278,  0.00656062,  1.02603605, ...,  0.9315193 ,
        -0.81816963, -0.26062993],
       ...,
       [-2.38832904, -1.9519484 ,  1.22782096, ..., -1.07351507,
         1.22224044, -0.26062993],
       [ 0.41870278,  0.98581513,  1.1388443 , ...,  0.9315193 ,
        -0.81816963, -0.26062993],
       [ 0.41870278,  0.78996423,  0.40293484, ..., -1.07351507,
         1.22224044, -0.26062993]], shape=(112723, 228))

In [23]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [24]:
#ANN Implementation
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [25]:
(X_train.shape[1],)

(228,)

In [26]:
## Build Our ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## HL1 Connected wwith input layer
    Dense(32,activation='relu'), ## HL2
    Dense(1,activation='linear')  ## output layer
]

)
model.summary()

c:\Users\LENOVO\OneDrive\Desktop\Udemy\Cars\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │        14,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 16,769 (65.50 KB)

 Trainable params: 16,769 (65.50 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.001)
loss=tensorflow.keras.losses.MeanSquaredError()
## compile the model
model.compile(
    optimizer=opt,
    loss='mean_squared_error',
    metrics=['mean_absolute_error']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [28]:
## Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [175]:
## Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [176]:
### Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 41s 11ms/step - accuracy: 0.0000e+00 - loss: -502619084685312.0000 - val_accuracy: 0.0000e+00 - val_loss: -1805801551298560.0000
Epoch 2/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 53s 14ms/step - accuracy: 0.0000e+00 - loss: -5316612240441344.0000 - val_accuracy: 0.0000e+00 - val_loss: -10040740184850432.0000
Epoch 3/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 30s 8ms/step - accuracy: 0.0000e+00 - loss: -17923821944176640.0000 - val_accuracy: 0.0000e+00 - val_loss: -27243319008428032.0000
Epoch 4/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.0000e+00 - loss: -40828672080347136.0000 - val_accuracy: 0.0000e+00 - val_loss: -55924580182654976.0000
Epoch 5/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -76415405295403008.0000 - val_accuracy: 0.0000e+00 - val_loss: -98427121277337600.0000
Epoch 6/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -127317184434143232.0000 - val_accuracy: 0.0000e+00 - val_loss: -157258320577560576.0000
Epoch 7/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -195929192498462720.0000 - val_accuracy: 0.0000e+00 - val_loss: -234984910668955648.0000
Epoch 8/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -284611539787317248.0000 - val_accuracy: 0.0000e+00 - val_loss: -333996997902073856.0000
Epoch 9/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -396289794813984768.0000 - val_accuracy: 0.0000e+00 - val_loss: -457063066656309248.0000
Epoch 10/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -533597425365942272.0000 - val_accuracy: 0.0000e+00 - val_loss: -606811258959691776.0000
Epoch 11/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -698522142307778560.0000 - val_accuracy: 0.0000e+00 - val_loss: -784979146781491200.0000
Epoch 12/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -893844541826662400.0000 - val_accuracy: 0.0000e+00 - val_loss: -994848909769572352.0000
Epoch 13/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -1121611193019006976.0000 - val_accuracy: 0.0000e+00 - val_loss: -1238085277247864832.0000
Epoch 14/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -1385041740808847360.0000 - val_accuracy: 0.0000e+00 - val_loss: -1517889683479068672.0000
Epoch 15/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -1685422132764344320.0000 - val_accuracy: 0.0000e+00 - val_loss: -1835220284127313920.0000
Epoch 16/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -2026164909380730880.0000 - val_accuracy: 0.0000e+00 - val_loss: -2194020752523526144.0000
Epoch 17/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -2408333710718926848.0000 - val_accuracy: 0.0000e+00 - val_loss: -2595200934539689984.0000
Epoch 18/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -2835886503761018880.0000 - val_accuracy: 0.0000e+00 - val_loss: -3042721683375915008.0000
Epoch 19/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -3310871953547460608.0000 - val_accuracy: 0.0000e+00 - val_loss: -3538700108671483904.0000
Epoch 20/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -3835431908729159680.0000 - val_accuracy: 0.0000e+00 - val_loss: -4084476789978562560.0000
Epoch 21/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -4411794804497711104.0000 - val_accuracy: 0.0000e+00 - val_loss: -4683096000116555776.0000
Epoch 22/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -5042044765143564288.0000 - val_accuracy: 0.0000e+00 - val_loss: -5336975565154942976.0000
Epoch 23/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -5729566637212827648.0000 - val_accuracy: 0.0000e+00 - val_loss: -6048477236070187008.0000
Epoch 24/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -6476722171681964032.0000 - val_accuracy: 0.0000e+00 - val_loss: -6820355839245680640.0000
Epoch 25/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -7284851123469418496.0000 - val_accuracy: 0.0000e+00 - val_loss: -7653662507797577728.0000
Epoch 26/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -8157122285086441472.0000 - val_accuracy: 0.0000e+00 - val_loss: -8551799680458031104.0000
Epoch 27/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -9096328416067584000.0000 - val_accuracy: 0.0000e+00 - val_loss: -9518219273982443520.0000
Epoch 28/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -10104726264028856320.0000 - val_accuracy: 0.0000e+00 - val_loss: -10553533716347486208.0000
Epoch 29/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -11182924958412046336.0000 - val_accuracy: 0.0000e+00 - val_loss: -11659881007913369600.0000
Epoch 30/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -12333843152833085440.0000 - val_accuracy: 0.0000e+00 - val_loss: -12838592657261330432.0000
Epoch 31/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -13562844265012264960.0000 - val_accuracy: 0.0000e+00 - val_loss: -14098221765343838208.0000
Epoch 32/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -14868492332763709440.0000 - val_accuracy: 0.0000e+00 - val_loss: -15432867253254619136.0000
Epoch 33/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -16253960546645180416.0000 - val_accuracy: 0.0000e+00 - val_loss: -16849460442295173120.0000
Epoch 34/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -17723655749260804096.0000 - val_accuracy: 0.0000e+00 - val_loss: -18350305908837318656.0000
Epoch 35/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -19278388280680251392.0000 - val_accuracy: 0.0000e+00 - val_loss: -19936978153532030976.0000
Epoch 36/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -20920229620810252288.0000 - val_accuracy: 0.0000e+00 - val_loss: -21611351843704668160.0000
Epoch 37/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -22654775184324558848.0000 - val_accuracy: 0.0000e+00 - val_loss: -23378623271308099584.0000
Epoch 38/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -24478790208014254080.0000 - val_accuracy: 0.0000e+00 - val_loss: -25236045856296140800.0000
Epoch 39/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -26399320362390126592.0000 - val_accuracy: 0.0000e+00 - val_loss: -27188481639086817280.0000
Epoch 40/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -28416849432568397824.0000 - val_accuracy: 0.0000e+00 - val_loss: -29242173646702641152.0000
Epoch 41/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -30533809538269708288.0000 - val_accuracy: 0.0000e+00 - val_loss: -31393163637283618816.0000
Epoch 42/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -32753646548935507968.0000 - val_accuracy: 0.0000e+00 - val_loss: -33645664939387387904.0000
Epoch 43/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -35076600158100652032.0000 - val_accuracy: 0.0000e+00 - val_loss: -36003666581199519744.0000
Epoch 44/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.0000e+00 - loss: -37500757215532810240.0000 - val_accuracy: 0.0000e+00 - val_loss: -38466119628627116032.0000
Epoch 45/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - accuracy: 0.0000e+00 - loss: -40042779720439300096.0000 - val_accuracy: 0.0000e+00 - val_loss: -41043502427482882048.0000
Epoch 46/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -42693750633518858240.0000 - val_accuracy: 0.0000e+00 - val_loss: -43730079925116338176.0000
Epoch 47/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -45458226330956988416.0000 - val_accuracy: 0.0000e+00 - val_loss: -46531890639387230208.0000
Epoch 48/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -48334460788288782336.0000 - val_accuracy: 0.0000e+00 - val_loss: -49443564555505500160.0000
Epoch 49/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -51331918601606135808.0000 - val_accuracy: 0.0000e+00 - val_loss: -52481330465097121792.0000
Epoch 50/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -54451501370443825152.0000 - val_accuracy: 0.0000e+00 - val_loss: -55638424172628017152.0000
Epoch 51/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -57696424066801467392.0000 - val_accuracy: 0.0000e+00 - val_loss: -58918179397353603072.0000
Epoch 52/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -61063911523330555904.0000 - val_accuracy: 0.0000e+00 - val_loss: -62325843008761626624.0000
Epoch 53/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -64562786221332365312.0000 - val_accuracy: 0.0000e+00 - val_loss: -65862686042293796864.0000
Epoch 54/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -68184960153272975360.0000 - val_accuracy: 0.0000e+00 - val_loss: -69522766737113612288.0000
Epoch 55/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -71942549937290477568.0000 - val_accuracy: 0.0000e+00 - val_loss: -73319120903079985152.0000
Epoch 56/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -75833941490315296768.0000 - val_accuracy: 0.0000e+00 - val_loss: -77249778215355940864.0000
Epoch 57/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -79867073286299975680.0000 - val_accuracy: 0.0000e+00 - val_loss: -81322967418963755008.0000
Epoch 58/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -84040230087105183744.0000 - val_accuracy: 0.0000e+00 - val_loss: -85533314101066858496.0000
Epoch 59/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -88351942945196212224.0000 - val_accuracy: 0.0000e+00 - val_loss: -89884873260548489216.0000
Epoch 60/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -92809530209967538176.0000 - val_accuracy: 0.0000e+00 - val_loss: -94381286479919841280.0000
Epoch 61/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -97412367358814584832.0000 - val_accuracy: 0.0000e+00 - val_loss: -99022817641971580928.0000
Epoch 62/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -102168793087922405376.0000 - val_accuracy: 0.0000e+00 - val_loss: -103821244715260444672.0000
Epoch 63/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -107073248266500964352.0000 - val_accuracy: 0.0000e+00 - val_loss: -108764200392997208064.0000
Epoch 64/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -112133649378270248960.0000 - val_accuracy: 0.0000e+00 - val_loss: -113867711156668334080.0000
Epoch 65/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -117353550044811231232.0000 - val_accuracy: 0.0000e+00 - val_loss: -119121283267298328576.0000
Epoch 66/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -122723775941101748224.0000 - val_accuracy: 0.0000e+00 - val_loss: -124533352178095489024.0000
Epoch 67/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -128256650393465913344.0000 - val_accuracy: 0.0000e+00 - val_loss: -130104463246827192320.0000
Epoch 68/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -133953070603391991808.0000 - val_accuracy: 0.0000e+00 - val_loss: -135845092620282888192.0000
Epoch 69/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -139816361494042378240.0000 - val_accuracy: 0.0000e+00 - val_loss: -141741966994092064768.0000
Epoch 70/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -145844227285138276352.0000 - val_accuracy: 0.0000e+00 - val_loss: -147811095257555140608.0000
Epoch 71/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -152043317823004475392.0000 - val_accuracy: 0.0000e+00 - val_loss: -154047630763416879104.0000
Epoch 72/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -158419746392291409920.0000 - val_accuracy: 0.0000e+00 - val_loss: -160465330601164013568.0000
Epoch 73/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -164967135825557979136.0000 - val_accuracy: 0.0000e+00 - val_loss: -167050173798519144448.0000
Epoch 74/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -171692487812849860608.0000 - val_accuracy: 0.0000e+00 - val_loss: -173807297273807241216.0000
Epoch 75/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -178591316346725728256.0000 - val_accuracy: 0.0000e+00 - val_loss: -180757442214374670336.0000
Epoch 76/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -185682251552206618624.0000 - val_accuracy: 0.0000e+00 - val_loss: -187880342421898264576.0000
Epoch 77/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -192957288984642322432.0000 - val_accuracy: 0.0000e+00 - val_loss: -195195718736933814272.0000
Epoch 78/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -200416833264311861248.0000 - val_accuracy: 0.0000e+00 - val_loss: -202690148321529430016.0000
Epoch 79/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -208068361070284111872.0000 - val_accuracy: 0.0000e+00 - val_loss: -210383492753729257472.0000
Epoch 80/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.0000e+00 - loss: -215911432597907963904.0000 - val_accuracy: 0.0000e+00 - val_loss: -218267237415487799296.0000
Epoch 81/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -223955406890159046656.0000 - val_accuracy: 0.0000e+00 - val_loss: -226342349877037498368.0000
Epoch 82/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -232182515839132499968.0000 - val_accuracy: 0.0000e+00 - val_loss: -234610448619494440960.0000
Epoch 83/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -240611512715151671296.0000 - val_accuracy: 0.0000e+00 - val_loss: -243074964119137288192.0000
Epoch 84/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -249255134260912717824.0000 - val_accuracy: 0.0000e+00 - val_loss: -251757147736707694592.0000
Epoch 85/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -258089507879953367040.0000 - val_accuracy: 0.0000e+00 - val_loss: -260620882714256474112.0000
Epoch 86/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -267123922246505070592.0000 - val_accuracy: 0.0000e+00 - val_loss: -269686716725083504640.0000
Epoch 87/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -276367912325403901952.0000 - val_accuracy: 0.0000e+00 - val_loss: -278973913212907421696.0000
Epoch 88/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -285823712324277501952.0000 - val_accuracy: 0.0000e+00 - val_loss: -288460218062382039040.0000
Epoch 89/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -295489439879219118080.0000 - val_accuracy: 0.0000e+00 - val_loss: -298164120661040037888.0000
Epoch 90/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -305375544748739133440.0000 - val_accuracy: 0.0000e+00 - val_loss: -308085937668230217728.0000
Epoch 91/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -315481446390698082304.0000 - val_accuracy: 0.0000e+00 - val_loss: -318222696004511072256.0000
Epoch 92/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -325818263066676035584.0000 - val_accuracy: 0.0000e+00 - val_loss: -328595998874345144320.0000
Epoch 93/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -336351760382630559744.0000 - val_accuracy: 0.0000e+00 - val_loss: -339164012059318812672.0000
Epoch 94/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -347116735682557509632.0000 - val_accuracy: 0.0000e+00 - val_loss: -349957029303800561664.0000
Epoch 95/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -358122055428223270912.0000 - val_accuracy: 0.0000e+00 - val_loss: -360990566915881566208.0000
Epoch 96/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -369341964659258818560.0000 - val_accuracy: 0.0000e+00 - val_loss: -372249319693703184384.0000
Epoch 97/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -380813758810078314496.0000 - val_accuracy: 0.0000e+00 - val_loss: -383747853967310192640.0000
Epoch 98/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.0000e+00 - loss: -392506194158266875904.0000 - val_accuracy: 0.0000e+00 - val_loss: -395464601716612136960.0000
Epoch 99/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -404418039250801393664.0000 - val_accuracy: 0.0000e+00 - val_loss: -407407584978445271040.0000
Epoch 100/100
3523/3523 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.0000e+00 - loss: -416596511515025080320.0000 - val_accuracy: 0.0000e+00 - val_loss: -419621347167874056192.0000

In [179]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [180]:
## Load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [182]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 22696), started 0:00:51 ago. (Use '!kill 22696' to kill it.)