In [16]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [17]:
### Load the trained model, scaler pickle,onehot
model=load_model('model.h5')

with open('label_encoder_accidental.pkl','rb') as file:
    label_encoder_accidental=pickle.load(file)

with open('label_encoder_transmission.pkl','rb') as file:
    label_encoder_transmission=pickle.load(file)

with open('onehot_encoder_brand.pkl','rb') as file:
    onehot_encoder_brand=pickle.load(file)

with open('onehot_encoder_fuel_type.pkl','rb') as file:
    onehot_encoder_fuel_type=pickle.load(file)

with open('onehot_encoder_model_name.pkl','rb') as file:
    onehot_encoder_model_name=pickle.load(file)

with open('onehot_encoder_model_variant.pkl','rb') as file:
    onehot_encoder_model_variant=pickle.load(file)

with open('onehot_encoder_car_type.pkl','rb') as file:
    onehot_encoder_car_type=pickle.load(file)

with open('onehot_encoder_state.pkl','rb') as file:
    onehot_encoder_state=pickle.load(file)

with open('onehot_encoder_owner.pkl','rb') as file:
    onehot_encoder_owner=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [18]:
# Example input data
input_data = {
    'Brand': 'Maruti Suzuki',
    'Model_Name': 'Dzire',
    'Model_Variant': 'Base',
    'Car_Type': 'Sedan',
    'Transmission': 'Manual',
    'Fuel_Type': 'Petrol',
    'Year': 2020,
    'Kilometers': 65203,
    'Owner': '1st',
    'State': 'Bihar',
    'Accidental': 'No',

}

In [19]:
# One-hot encode 'Brand'
brand_encoded = onehot_encoder_brand.transform([[input_data['Brand']]]).toarray()
brand_encoded_df = pd.DataFrame(brand_encoded, columns=onehot_encoder_brand.get_feature_names_out(['Brand']))

# One-hot encode 'Fuel_Type'
fuel_type_encoded = onehot_encoder_fuel_type.transform([[input_data['Fuel_Type']]]).toarray()
fuel_type_encoded_df = pd.DataFrame(fuel_type_encoded, columns=onehot_encoder_fuel_type.get_feature_names_out(['Fuel_Type']))


# One-hot encode 'Model_Name'
model_name_encoded = onehot_encoder_model_name.transform([[input_data['Model_Name']]]).toarray()
model_name_encoded_df = pd.DataFrame(model_name_encoded, columns=onehot_encoder_model_name.get_feature_names_out(['Model_Name']))

# One-hot encode 'Model_Variant'
model_variant_encoded = onehot_encoder_model_variant.transform([[input_data['Model_Variant']]]).toarray()
model_variant_encoded_df = pd.DataFrame(model_variant_encoded, columns=onehot_encoder_model_variant.get_feature_names_out(['Model_Variant']))

# One-hot encode 'Car_Type'
car_type_encoded = onehot_encoder_car_type.transform([[input_data['Car_Type']]]).toarray()
car_type_encoded_df = pd.DataFrame(car_type_encoded, columns=onehot_encoder_car_type.get_feature_names_out(['Car_Type']))

# One-hot encode 'State'
state_encoded = onehot_encoder_state.transform([[input_data['State']]]).toarray()
state_encoded_df = pd.DataFrame(state_encoded, columns=onehot_encoder_state.get_feature_names_out(['State']))

# One-hot encode 'Owner'
owner_encoded = onehot_encoder_owner.transform([[input_data['Owner']]]).toarray()
owner_encoded_df = pd.DataFrame(owner_encoded, columns=onehot_encoder_owner.get_feature_names_out(['Owner']))

c:\Users\LENOVO\OneDrive\Desktop\Udemy\Cars\.venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
c:\Users\LENOVO\OneDrive\Desktop\Udemy\Cars\.venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
c:\Users\LENOVO\OneDrive\Desktop\Udemy\Cars\.venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
c:\Users\LENOVO\OneDrive\Desktop\Udemy\Cars\.venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
c:\Users\LENOVO\OneDrive\Desktop\Udemy\Cars\.venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
c:\Users\LENOVO\OneDrive\Desktop\Udemy\Cars\.venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
c:\Users\LENOVO\OneDrive\Desktop\Udemy\Cars\.venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [20]:

input_df=pd.DataFrame([input_data])
input_df

,Brand,Model_Name,Model_Variant,Car_Type,Transmission,Fuel_Type,Year,Kilometers,Owner,State,Accidental
0,Maruti Suzuki,Dzire,Base,Sedan,Manual,Petrol,2020,65203,1st,Bihar,No

In [21]:

## Encode categorical variables
input_df['Accidental']=label_encoder_accidental.transform(input_df['Accidental'])
input_df

## Encode categorical variables
input_df['Transmission']=label_encoder_transmission.transform(input_df['Transmission'])
input_df

,Brand,Model_Name,Model_Variant,Car_Type,Transmission,Fuel_Type,Year,Kilometers,Owner,State,Accidental
0,Maruti Suzuki,Dzire,Base,Sedan,1,Petrol,2020,65203,1st,Bihar,0

In [22]:
## concatination one hot encoded 
input_df=pd.concat([input_df.drop("Brand",axis=1),brand_encoded_df],axis=1)
input_df

## concatination one hot encoded 
input_df=pd.concat([input_df.drop("Fuel_Type",axis=1),fuel_type_encoded_df],axis=1)
input_df

## concatination one hot encoded 
input_df=pd.concat([input_df.drop("Model_Name",axis=1),model_name_encoded_df],axis=1)
input_df

## concatination one hot encoded 
input_df=pd.concat([input_df.drop("Model_Variant",axis=1),model_variant_encoded_df],axis=1)
input_df

## concatination one hot encoded 
input_df=pd.concat([input_df.drop("Car_Type",axis=1),car_type_encoded_df],axis=1)
input_df

## concatination one hot encoded 
input_df=pd.concat([input_df.drop("State",axis=1),state_encoded_df],axis=1)
input_df

## concatination one hot encoded 
input_df=pd.concat([input_df.drop("Owner",axis=1),owner_encoded_df],axis=1)
input_df

,Transmission,Year,Kilometers,Accidental,Brand_Audi,Brand_BMW,Brand_Chevrolet,Brand_Ford,Brand_Honda,Brand_Hyundai,...,State_Punjab,State_Rajasthan,State_Tamil Nadu,State_Telangana,State_Uttar Pradesh,State_Uttarakhand,State_West Bengal,Owner_1st,Owner_2nd,Owner_3rd+
0,1,2020,65203,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [23]:

# Load the exact feature order used during training
with open("feature_columns.pkl", "rb") as file:
    feature_columns = pickle.load(file)

# Match the training feature order
input_df = input_df.reindex(
    columns=feature_columns,
    fill_value=0
)

print("Input shape:", input_df.shape)
print("Expected features:", scaler.n_features_in_)

Input shape: (1, 228)
Expected features: 228

In [24]:
## Scaling the input data
input_scaled=scaler.transform(input_df)
input_scaled

array([[ 0.41870278,  0.59411333, -0.61032456, -0.29421091, -0.0840642 ,
        -0.08544455, -0.0727221 , -0.19628861, -0.30495463, -0.43160535,
        -0.07972778, -0.12429536, -0.10219099, -0.2700349 ,  1.26737993,
        -0.12557707, -0.08238906, -0.1487444 , -0.10364355, -0.25950235,
        -0.28346686, -0.16249962, -0.33285177, -0.65153147, -0.14451458,
        -0.14052938,  0.88202341, -0.04205368, -0.04501952, -0.03436971,
        -0.03722689, -0.20967468, -0.11222393, -0.13069129, -0.07984039,
        -0.09743125, -0.05636593, -0.15158589, -0.21128347, -0.03111122,
        -0.11675716, -0.13090179, -0.06886155, -0.21096253, -0.13146157,
        -0.1531707 , -0.03305091, -0.04141374, -0.07278372,  4.66558932,
        -0.09536888, -0.09710597, -0.21155824, -0.12101649, -0.04021428,
        -0.04492048, -0.09710597, -0.12277796, -0.12314968, -0.15304932,
        -0.11455157, -0.06202538, -0.21050334, -0.12229313, -0.13267844,
        -0.07160414, -0.04619151, -0.07639169, -0.06151888, -0.06281316,
        -0.11526487, -0.04590129, -0.08106905, -0.03805413, -0.03758364,
        -0.03999236, -0.04826693, -0.20865817, -0.03195687, -0.11628787,
        -0.07235133, -0.04560925, -0.0729068 , -0.03358462, -0.04226485,
        -0.06274195, -0.04472176, -0.21038841, -0.11738012, -0.08000902,
        -0.03250847, -0.06259928, -0.11911568, -0.11145139, -0.1116959 ,
        -0.07418706, -0.12513902, -0.04043499, -0.08090258, -0.15020216,
        -0.14899345, -0.13212345, -0.21180986, -0.04320244, -0.03999236,
        -0.04541351, -0.04742878, -0.11738012, -0.05785131, -0.15256293,
        -0.15078781, -0.08438469, -0.08586493, -0.08680356, -0.04590129,
        -0.08023332, -0.04462207, -0.150449  , -0.0487264 ,  2.98156293,
        -0.0727221 , -0.17360693, -0.1533526 , -0.11250727, -0.11222393,
        -0.06970187, -0.04590129, -0.04676659, -0.04541351, -0.04580415,
        -0.04835917, -0.04770978, -0.04647993, -0.04560925, -0.07147887,
        -0.07197869, -0.28849476, -0.04541351, -0.03601236, -0.03488334,
        -0.03734618, -0.04972243, -0.04890899, -0.15109522, -0.04724052,
        -0.03965716, -0.0487264 , -0.04890899, -0.03897817, -0.03988094,
        -0.0405449 , -0.07364104, -0.07315235, -0.07490902, -0.07333598,
        -0.13163605, -0.04817452, -0.15047983, -0.1523192 , -0.04657568,
        -0.04531533, -0.04541351, -0.04900003, -0.07709347, -0.15131007,
        -0.06614277, -0.04432166, -0.0476163 , -0.07950209, -0.07893511,
        -0.07790442, -0.07955857, -0.07364104, -0.34516464, -0.17589823,
        -0.08834645, -0.08675168, -0.09056327, -0.08649178, -0.08633548,
        -0.0893607 , -0.11597401, -0.05620732, -0.10236811, -0.10214666,
        -0.0565241 , -0.05467787, -0.05548803, -0.10438429, -0.10486092,
        -0.10355607, -0.28655987, -0.34321393, -0.81183858, -0.15611769,
        -0.27186458, -0.57553713,  1.68135552, -0.1408245 , -0.07053236,
         9.92424972, -0.06918593, -0.0710387 , -0.42526758, -0.07129055,
        -0.31029335, -0.09913354, -0.0535233 , -0.05368974, -0.07129055,
        -0.39389082, -0.19943561, -0.13848057, -0.45992187, -0.06976609,
        -0.09881365, -0.04619151, -0.04482123, -0.13917764, -0.20010792,
        -0.32783027, -0.25052506, -0.20363038, -0.05061107, -0.22605067,
         0.9315193 , -0.81816963, -0.26062993]])

In [25]:
## PRedict Car Price
prediction = model.predict(input_scaled)

predicted_price = float(prediction[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

In [26]:
print("Predicted Car Price:", predicted_price)

Predicted Car Price: 768694.3125